Kenya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kisumu.urls'))
]

kisumu/urls.py
from django.urls import path
from . import views

app_name = 'Kisumu'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),

]

kisumu/models.py
from django.db import models

# Create your models here.

kisumu/views.py
from django.shortcuts import render
#create your views here

def home(request):
    return render(request, 'home.html',  {'bike': 'home'})

def about(request):
    return render(request, 'about.html',  {'bike': 'about'})

def contact(request):
    return render(request, 'contact.html', {'bike': 'contact'})

kisumu/templates/about.html
{% extends 'layout.html' %}

{% block body %}

    <p>About Us</p>

{% endblock %}

kisumu/templates/contact.html
{% extends 'layout.html' %}

{% block body %}

    <p> Contact Us</p>

{% endblock %}

kisumu/templates/home.html
{% extends 'layout.html' %}

{% block body %}

    <p> KARIBU KISUMU </p>

{% endblock %}

kisumu/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>

<a class="{% if bike == 'home' %}two {% endif %}" href="{% url 'Kisumu:home' %}">HOME</a>
<a class="{% if bike == 'about' %}two {% endif %}" href="{% url 'Kisumu:about' %}">ABOUT</a>
<a class="{% if bike == 'contact' %}two {% endif %}" href="{% url 'Kisumu:contact' %}">CONTACT</a>




{% block body %}

{% endblock %}

</body>
</html>